### ISSUE TITLE
Please use TOML for the color scheme file

### ISSUE THREAD

**Issue by wez** [hardhackerlabs/theme-wezterm#2]
Hi! I saw this mentioned on reddit.

Please see https://github.com/dracula/wezterm/issues/2#issuecomment-1221474633 for more info on toml vs lua. The TL;DR is that TOML is safer for users, and it can then be added to wezterm's theme aggregation automation and included in the next wezterm release.

**Comment by skoowoo** [comment]
Yes, You are right. The old config is lua, now is toml file. Because I have not updated the parent repo (themes), so what you see is still the old config(lua).

thanks for feedback.
